name: Build MacOS aarch64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: get-cmake
        uses: lukka/get-cmake@latest

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Build concurrentqueue
        run: |
          cd ext/concurrentqueue
          git pull origin master
          ./build_c_api.sh
          cd ..

      - name: build and test
        run: |
          ./build.sh --tests --reldebug --clean
          cat build/Testing/Temporary/LastTest.log
